### PR TITLE
Provide access to bigSlide components

### PR DESCRIPTION
**Pull request by fabrizim**
I think it'd be good to give developers access to the bigSlide internals. While it may be more appropriate to provide only a subset of functions through a more formal public API, I think providing access to all the MVC components to developers that want to access them is fine as long as they know that the internals are subject to change.

### CODE REVIEW

**Comment by fabrizim** [comment]
Also - I added the `return this;` for chainability.

**Comment by ascott1** [comment]
:+1: good change. Thanks for this! I'll merge once I have time to run a build and tag a new release.

**Comment by ascott1** [comment]
Hey @fabrizim I'm sorry to drag my feet on this. I'm looking at exposing things in a different way for testing purposes, but I'm going to keep this open for now because it's not set in stone. I really appreciate the contribution regardless!

**Comment by maximumhallinan** [comment]
Hey @ascott1, are you still thinking of exposing some or all of the internal components? If so, could you say more about "exposing things in a different way for testing purposes"? Having the ability to open and close the menu without triggering `click.bigSlide` on `menuLink` is a feature I (and I'm guessing others) would find especially valuable. Triggering the event works, of course, but it feels cleaner to call an API. I've been playing with this just now because I need those features for a project this weekend. Here's what I've come up with: [complete internals](https://github.com/maximumhallinan/bigSlide.js/blob/expose_all/src/jquery.big-slide.js#L143-L149) and [subset of internals](https://github.com/maximumhallinan/bigSlide.js/blob/expose_some/src/jquery.big-slide.js#L143-L148). I'm not submitting these as pull requests because it sounds like you already have something specific in mind. Would love to hear more about that.

**Comment by maximumhallinan** [comment]
[This](https://github.com/maximumhallinan/bigSlide.js/blob/expose_no_chaining/src/jquery.big-slide.js) is another option which I like more for simplicity but sacrifices chainability.

**Comment by ascott1** [comment]
At first glance, I like these solutions @maximumhallinan and they're in line with what I was thinking. I haven't had time to implement anything myself. If you submit a PR, I'll merge. I *think* my preference is for the full set of internals.

Than

**Comment by maximumhallinan** [comment]
Sounds good. Pull request is [here](https://github.com/ascott1/bigSlide.js/pull/46).

**Comment by ascott1** [comment]
Thanks again for doing this @fabrizim. I'm going to close this particular PR in favor of #46, but I really appreciate your work.

**Comment by fabrizim** [comment]
No problem! #46 is better and includes tests - nice work @maximumhallinan!

**Comment by maximumhallinan** [comment]
@fabrizim, thanks for kicking this off! @ascott1, thanks for the merge!

**Pull request closed without merging**
