### PR TITLE
Add destroy method

### PR DESCRIPTION
**Pull request by maximumhallinan**
This adds a destroy method to the bigSlide controller component and changes the name of the property exposing the bigSlide internals from `bigSlide` to `bigSlideAPI`. Exposing the bigSlide internal components on the jQuery object to which bigSlide is bound as a property called "bigSlide" has the unintended effect of overwriting the`bigSlide` method inherited from the jQuery object prototype (`$.fn.bigSlide`). This is a problem primarily for testing that the destroy method removes the property exposing the internal components.

The destroy method:
- unbinds bigSlide event handlers;
- removes inline CSS applied by bigSlide;
- preserves inline CSS not applied by bigSlide;
- removes the active class from the menu link;
- releases internal DOM references to avoid memory leaks;
- deletes the `bigSlideAPI` property on the jQuery object on which `$.fn.bigSlide` was called;
- returns a reference to the jQuery object on which `$.fn.bigSlide` was called so that the destroy method is chainable.

Tests have been added to  big-slide.spec.js.

### CODE REVIEW

**Comment by ascott1** [comment]
At first glance this looks great @maximumhallinan. Thank you!

I'm going to pull this down and take a closer look later today.

**Comment by maximumhallinan** [comment]
Thanks for taking a look! It might be good to reference `controller.destroy` directly on `bigSlideAPI`. This would enable one to call `foo.bigSlideAPI.destroy` rather than `foo.bigSlideAPI.controller.destroy`.

**Comment by ascott1** [comment]
> It might be good to reference controller.destroy directly on bigSlideAPI. This would enable one to call foo.bigSlideAPI.destroy rather than foo.bigSlideAPI.controller.destroy.

Yup, I agree! Mind making this change and then I'll merge?

**Comment by ascott1** [comment]
Actually, I'm going to merge now as I just reviewed it and have a few minutes to bump the version # and republish. If you want to add that with a new pull request, great. If not I can open an issue.

Thanks again!

**Comment by maximumhallinan** [comment]
Thanks for the merge. Second pull request is [here](https://github.com/ascott1/bigSlide.js/pull/52).

**Pull request merged**
